#!/usr/bin/env bash

main_major() {
  sass major
}

main_minor() {
  sass minor
}

sass() {
  node_modules/node-sass/bin/node-sass --include-path node_modules/bourbon/app/assets/stylesheets --output public/styles --output-style compressed "client/styles/${1}.scss" "public/styles/${1}.css"
}

. tasks/execute
