#!/usr/bin/env bash

. tasks/library

sass() {
  node_modules/node-sass/bin/node-sass --include-path node_modules/bourbon/app/assets/stylesheets --output public/styles --output-style compressed "client/styles/${1}.scss" "public/styles/${1}.css"
}

header major
sass major &> $TASK_LOG
footer

header minor
sass minor &> $TASK_LOG
footer
