#!/usr/bin/env bash

main() {
  local PARTIALS=$(find client/templates/partials -name *.html | paste -s -d ':' -)

  if [ ! -z "$PARTIALS" ]; then
    PARTIALS="-p ${PARTIALS/:/ -p }"
  fi

  node_modules/mustache/bin/mustache $PARTIALS package.json client/templates/main.html > public/index.html
  node_modules/html-minifier/cli.js --collapse-whitespace --output public/index.html --remove-comments public/index.html
}

. tasks/execute
