#!/usr/bin/env bash

node_modules/.bin/vigilia 'client/images/**/*':'make images' \
                          'client/scripts/**/*.js':'make scripts templates' \
                          'client/styles/**/*.scss':'make styles templates' \
                          'client/templates/**/*.html':'make templates'
